//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIKIEMTRA_CAUHOI
    {
        public int MaBaiKiemTra { get; set; }
        public int MaCauHoi { get; set; }
        public string MoTa { get; set; }
    
        public virtual BAI_KIEM_TRA BAI_KIEM_TRA { get; set; }
        public virtual CAU_HOI CAU_HOI { get; set; }
    }
}
