//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KET_QUA_PHUC_KHAO
    {
        public string maSV { get; set; }
        public int maBaiKiemTra { get; set; }
        public int thuTuCauHoi { get; set; }
        public string tenCauHoi { get; set; }
        public string dapAnA { get; set; }
        public string dapAnB { get; set; }
        public string dapAnC { get; set; }
        public string dapAnD { get; set; }
        public string dapAnChon { get; set; }
        public string dapAnDung { get; set; }
    
        public virtual BAI_KIEM_TRA BAI_KIEM_TRA { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
