//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_HOC_PHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP_HOC_PHAN()
        {
            this.BAI_KIEM_TRA = new HashSet<BAI_KIEM_TRA>();
            this.SINHVIEN_LOPHOCPHAN = new HashSet<SINHVIEN_LOPHOCPHAN>();
            this.THOI_KHOA_BIEU = new HashSet<THOI_KHOA_BIEU>();
            this.THONG_BAO = new HashSet<THONG_BAO>();
        }
    
        public string MaLopHP { get; set; }
        public string MaMH { get; set; }
        public string MaGV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAI_KIEM_TRA> BAI_KIEM_TRA { get; set; }
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN_LOPHOCPHAN> SINHVIEN_LOPHOCPHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOI_KHOA_BIEU> THOI_KHOA_BIEU { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONG_BAO> THONG_BAO { get; set; }
    }
}
