//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PBL3Entities : DbContext
    {
        public PBL3Entities()
            : base("name=PBL3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAI_KIEM_TRA> BAI_KIEM_TRA { get; set; }
        public virtual DbSet<CAU_HOI> CAU_HOI { get; set; }
        public virtual DbSet<CHUONG_TRINH_DAO_TAO> CHUONG_TRINH_DAO_TAO { get; set; }
        public virtual DbSet<GIANG_VIEN> GIANG_VIEN { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<LAM_BAI_KIEM_TRA> LAM_BAI_KIEM_TRA { get; set; }
        public virtual DbSet<LOP_HOC_PHAN> LOP_HOC_PHAN { get; set; }
        public virtual DbSet<LOP_SINH_HOAT> LOP_SINH_HOAT { get; set; }
        public virtual DbSet<MON_HOC> MON_HOC { get; set; }
        public virtual DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual DbSet<PHU_HUYNH> PHU_HUYNH { get; set; }
        public virtual DbSet<SINH_VIEN> SINH_VIEN { get; set; }
        public virtual DbSet<SINHVIEN_LOPHOCPHAN> SINHVIEN_LOPHOCPHAN { get; set; }
        public virtual DbSet<THOI_KHOA_BIEU> THOI_KHOA_BIEU { get; set; }
        public virtual DbSet<THONG_BAO> THONG_BAO { get; set; }
        public virtual DbSet<THONG_TIN_DANG_NHAP> THONG_TIN_DANG_NHAP { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<ward> wards { get; set; }
    }
}
