//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_DUNG
    {
        public string MaNguoiDung { get; set; }
        public string MaCCCD { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public byte[] AnhCaNhan { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public bool GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string QuocTinh { get; set; }
        public string NoiSinh { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
        public string EmailCaNhan { get; set; }
        public string EmailTruongCap { get; set; }
        public string MkEmailTruongCap { get; set; }
    
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
        public virtual THONG_TIN_DANG_NHAP THONG_TIN_DANG_NHAP { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
