//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHU_HUYNH
    {
        public string MaSV { get; set; }
        public string TenPH { get; set; }
        public bool GioiTinh { get; set; }
        public string Sdt { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string MoiQuanHe { get; set; }
    
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
