//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN_LOPHOCPHAN
    {
        public string MaLopHP { get; set; }
        public string MaSV { get; set; }
        public byte KiHoc { get; set; }
        public byte NamHoc { get; set; }
    
        public virtual LOP_HOC_PHAN LOP_HOC_PHAN { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
