//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOI_KHOA_BIEU
    {
        public string Thu { get; set; }
        public string MaPhongHoc { get; set; }
        public byte TietBD { get; set; }
        public byte TietKetThuc { get; set; }
        public string MaLopHP { get; set; }
    
        public virtual LOP_HOC_PHAN LOP_HOC_PHAN { get; set; }
    }
}
