//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONG_TIN_DANG_NHAP
    {
        public string TaiKhoan { get; set; }
        public string MkUngDung { get; set; }
        public string VaiTro { get; set; }
        public string MaXacThucDeLayLaiMK { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
    }
}
