//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONG_BAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONG_BAO()
        {
            this.LOP_HOC_PHAN = new HashSet<LOP_HOC_PHAN>();
        }
    
        public int MaTB { get; set; }
        public string TieuDe { get; set; }
        public string NDThongBao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string MaGVThongBao { get; set; }
    
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_HOC_PHAN> LOP_HOC_PHAN { get; set; }
    }
}
