//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ward
    {
        public int ward_id { get; set; }
        public Nullable<int> district_id { get; set; }
        public string xaPhuong { get; set; }
    
        public virtual district district { get; set; }
    }
}
