CREATE TABLE [dbo].[LOP_SINH_HOAT] (
    [MaLopSH] NVARCHAR (9) NOT NULL,
    [MaGVCN]  NVARCHAR (9) NOT NULL,
    PRIMARY KEY CLUSTERED ([MaLopSH] ASC),
    FOREIGN KEY ([MaGVCN]) REFERENCES [dbo].[GIANG_VIEN] ([MaGV])
);

