//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAI_KIEM_TRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAI_KIEM_TRA()
        {
            this.LAM_BAI_KIEM_TRA = new HashSet<LAM_BAI_KIEM_TRA>();
            this.LOP_HOC_PHAN = new HashSet<LOP_HOC_PHAN>();
        }
    
        public int MaBaiKiemTra { get; set; }
        public string TenBaiKiemTra { get; set; }
        public string TieuDeBaiKiemTra { get; set; }
        public System.DateTime NgayKiemTra { get; set; }
        public byte ThoiGianLamBai { get; set; }
        public byte SoCauHoi { get; set; }
        public string MaGV { get; set; }
    
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAM_BAI_KIEM_TRA> LAM_BAI_KIEM_TRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_HOC_PHAN> LOP_HOC_PHAN { get; set; }
    }
}
