//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONG_TIN_DANG_NHAP
    {
        public string TaiKhoan { get; set; }
        public string MkUngDung { get; set; }
        public string EmailTruongCap { get; set; }
        public string MkEmail { get; set; }
        public string VaiTro { get; set; }
        public string MaXacThuc { get; set; }
    
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
        public virtual GIANG_VIEN GIANG_VIEN1 { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
